[package]
name = "opsline"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["cargo"] }
env_logger = "0.11.8"
figment = { version = "0.10.19", features = ["yaml"] }
git2 = { version = "0.20.2", default-features = false, features = ["vendored-libgit2"] }
kube = { version = "2.0.1", features = ["config"] }
libc = "0.2.175"
log = "0.4.22"
serde = { version = "1.0.226", features = ["derive"] }
ureq = { version = "3.1.0", features = ["json"] }
